In [1]:
#Dependencies 
%matplotlib inline 
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import datetime

In [2]:
data_file = "US_Accidents.csv"

In [5]:
data_file_df = pd.read_csv(data_file)
data_file_df.head()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201,3,2/8/2016 5:46,2/8/2016 11:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201,2,2/8/2016 6:07,2/8/2016 6:37,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201,2,2/8/2016 6:49,2/8/2016 7:19,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201,3,2/8/2016 7:23,2/8/2016 7:53,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201,2,2/8/2016 7:39,2/8/2016 8:09,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day

In [6]:
new_data_df = data_file_df[["ID","Start_Time","End_Time", "Start_Lat", "Start_Lng", "City", "State", "Temperature(F)", "Weather_Condition","Astronomical_Twilight"]]
new_data_df.head()

,ID,Start_Time,End_Time,Start_Lat,Start_Lng,City,State,Temperature(F),Weather_Condition,Astronomical_Twilight
0,A-1,2/8/2016 5:46,2/8/2016 11:00,39.865147,-84.058723,Dayton,OH,36.9,Light Rain,Night
1,A-2,2/8/2016 6:07,2/8/2016 6:37,39.928059,-82.831184,Reynoldsburg,OH,37.9,Light Rain,Day
2,A-3,2/8/2016 6:49,2/8/2016 7:19,39.063148,-84.032608,Williamsburg,OH,36.0,Overcast,Day
3,A-4,2/8/2016 7:23,2/8/2016 7:53,39.747753,-84.205582,Dayton,OH,35.1,Mostly Cloudy,Day
4,A-5,2/8/2016 7:39,2/8/2016 8:09,39.627781,-84.188354,Dayton,OH,36.0,Mostly Cloudy,Day

In [7]:
new_data_df["Year"] = pd.DatetimeIndex(new_data_df["Start_Time"]).year
new_data_df.head()

C:\Users\nidas\Anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,ID,Start_Time,End_Time,Start_Lat,Start_Lng,City,State,Temperature(F),Weather_Condition,Astronomical_Twilight,Year
0,A-1,2/8/2016 5:46,2/8/2016 11:00,39.865147,-84.058723,Dayton,OH,36.9,Light Rain,Night,2016
1,A-2,2/8/2016 6:07,2/8/2016 6:37,39.928059,-82.831184,Reynoldsburg,OH,37.9,Light Rain,Day,2016
2,A-3,2/8/2016 6:49,2/8/2016 7:19,39.063148,-84.032608,Williamsburg,OH,36.0,Overcast,Day,2016
3,A-4,2/8/2016 7:23,2/8/2016 7:53,39.747753,-84.205582,Dayton,OH,35.1,Mostly Cloudy,Day,2016
4,A-5,2/8/2016 7:39,2/8/2016 8:09,39.627781,-84.188354,Dayton,OH,36.0,Mostly Cloudy,Day,2016

In [8]:
data = new_data_df.loc[new_data_df["Year"]>2017]

In [12]:
data.index.name='ID'
data = data.reset_index(drop=True)
final_data = data.drop(data.index[172867:536348])
final_data

,ID,Start_Time,End_Time,Start_Lat,Start_Lng,City,State,Temperature(F),Weather_Condition,Astronomical_Twilight,Year
0,A-512230,3/3/2019 9:53,3/3/2019 10:22,42.338089,-79.586700,Westfield,NY,26.1,Mostly Cloudy,Day,2019
1,A-512231,3/3/2019 15:25,3/3/2019 15:55,42.743877,-78.845070,Hamburg,NY,28.0,Overcast,Day,2019
2,A-512232,3/3/2019 17:36,3/3/2019 18:06,43.004314,-78.946648,Grand Island,NY,25.0,Light Snow,Day,2019
3,A-512233,3/3/2019 17:48,3/3/2019 18:18,43.074436,-78.990921,Niagara Falls,NY,25.0,Light Snow,Day,2019
4,A-512234,3/3/2019 17:54,3/3/2019 18:24,41.946899,-78.672333,Bradford,PA,24.1,Snow,Day,2019
5,A-512235,3/3/2019 18:37,3/3/2019 19:07,42.461056,-79.306686,Dunkirk,NY,21.9,Light Snow,Day,2019
6,A-512236,3/3/2019 19:04,3/3/2019 19:34,42.877087,-78.871170,Buffalo,NY,23.0,Light Snow,Day,2019
7,A-512237,3/3/2019 7:27,3/3/2019 7:56,41.800339,-71.440254,Providence,RI,33.1,Partly Cloudy,Day,2019
8,A-512238,3/3/2019 7:37,3/3/2019 8:06,41.811039,-71.354225,East Providence,RI,33.1,Partly Cloudy,Day,2019
9,A-512239,3/3/2019 13:09,3/3/2019 13:38,41.811123,-71.440117,Providence,RI,39.9,Mostly Cloudy,Day,2019
10,A-512240,3/3/2019 13:12,3/3/2019 13:41,41.818142,-71.395752,Providence,RI,39.9,Mostly Cloudy,Day,2019
11,A-512241,3/3/2019 18:08,3/3/2019 18:37,42.956818,-71.436157,Manchester,NH,39.0,Overcast,Day,2019
12,A-512242,3/3/2019 1:20,3/3/2019 1:50,43.025536,-83.654694,Flint,MI,19.0,Clear,Night,2019
13,A-512243,3/3/2019 2:30,3/3/2019 3:00,43.031761,-83.677521,Flint,MI,17.1,Clear,Night,2019
14,A-512244,3/3/2019 3:34,3/3/2019 4:04,42.378071,-83.036903,Detroit,MI,21.9,Partly Cloudy,Night,2019
15,A-512245,3/3/2019 10:27,3/3/2019 10:57,41.794415,-83.462059,Erie,MI,27.5,Light Snow,Day,2019
16,A-512246,3/3/2019 14:25,3/3/2019 14:55,42.151798,-83.383911,New Boston,MI,27.0,Light Snow,Day,2019
17,A-512247,3/3/2019 15:25,3/3/2019 15:54,42.062115,-83.259033,South Rockwood,MI,26.6,Light Snow,Day,2019
18,A-512248,3/3/2019 16:04,3/3/2019 16:33,41.965714,-83.349152,Monroe,MI,27.1,Light Snow,Day,2019
19,A-512249,3/3/2019 16:41,3/3/2019 17:11,42.245937,-83.764130,Ann Arbor,MI,24.1,Light Snow,Day,2019
20,A-512250,3/3/2019 17:18,3/3/2019 17:48,42.367279,-83.138763,Detroit,MI,25.0,Light Snow,Day,2019
21,A-512251,3/3/2019 19:05,3/3/2019 19:35,42.937733,-83.723526,Flint,MI,14.0,Clear,Day,2019
22,A-512252,3/3/2019 20:29,3/3/2019 20:58,43.026810,-83.754204,Flint,MI,12.0,Clear,Night,2019
23,A-512253,3/3/2019 23:35,3/4/2019 0:05,42.384739,-83.291168,Redford,MI,15.1,Clear,Night,2019
24,A-512254,3/3/2019 12:48,3/3/2019 13:18,41.767467,-72.664513,East Hartford,CT,41.0,Clear,Day,2019
25,A-512255,3/3/2019 15:58,3/3/2019 16:27,42.743481,-73.645767,Troy,NY,37.0,Overcast,Day,2019
26,A-512256,3/3/2019 21:54,3/3/2019 22:23,42.501499,-73.557991,Nassau,NY,30.0,Light Snow,Night,2019
27,A-512257,3/3/2019 23:47,3/4/2019 0:16,42.579559,-73.472633,Averill Park,NY,32.0,Light Snow,Night,2019
28,A-512258,3/3/2019 11:32,3/3/2019 12:01,42.702297,-73.849915,Albany,NY,34.0,Mostly Cloudy,Day,2019
29,A-512259,3/3/2019 15:14,3/3/2019 15:43,43.051701,-76.049881,East Syracuse,NY,28.9,Overcast,Day,2019
...,...,...,...,...,...,...,...,...,...,...,...
172837,A-685067,1/30/2019 15:27,1/30/2019 16:12,33.988949,-118.342003,Los Angeles,CA,64.0,Clear,Day,2019
172838,A-685068,1/30/2019 15:43,1/30/2019 16:28,34.280270,-118.418640,Pacoima,CA,64.4,Clear,Day,2019
172839,A-685069,1/30/2019 15:45,1/30/2019 16:29,34.060234,-118.214859,Los Angeles,CA,64.0,Clear,Day,2019
172840,A-685070,1/30/2019 15:54,1/30/2019 16:38,34.280270,-118.418640,Pacoima,CA,64.4,Clear,Day,2019
172841,A-685071,1/30/2019 16:17,1/30/2019 17:02,33.968304,-117.848915,Diamond Bar,CA,59.0,Clear,Day,2019
172842,A-685072,1/30/2019 16:19,1/30/2019 17:04,34.030296,-117.700874,Chino,CA,66.9,Haze,Day,2019
172843,A-685073,1/30/2019 16:20,1/30/2019 17:05,33.923721,-118.261452,Los Angeles,CA,64.0,Clear,Day,2019
172844,A-685074,1/30/2019 16:58,1/30/2019 17:43,33.893661,-118.046768,Santa Fe Springs,CA,62.1,Clear,Day,2019
172845,A-685075,1/30/2019 16:57,1/30/2019 17:42,34.036858,-118.286255,Los Angeles,CA,63.0,Clear,Day,2019
172846,A-685076,1/30/2019 17:24,1/30/2019 18:08,34.992352,-117.541573,Boron,CA,62.6,Clear,Day,2019
172847,A-685077,1/30/2019 17:27,1/30/2019 18:12,34.100533,-118.248459,Los Angeles,CA,61.0,Clear,Day,2019
172848,A-685078,1/30/2019 17:31,1/30/2019 18:16,34.025826,-118.249275,Los Angeles,CA,61.0,Clear,Day,2019
172849,A-685079,1/30/2019 17:36,1/30/2019 18:21,34.070572,-118.263855,Los Angeles,CA,61.0,Clear,Day,2019
172850,A-685080,1/30/2019 17:46,1/30/2019 18:30,33.876804,-118.173920,Long Beach,CA,60.1,Haze,Day,2019
172851,A-685081,1/30/2019 17:49,1/30/2019 18:34,34.172081,-118.467560,Van Nuys,CA,63.0,Clear,Day,2019
172852,A-685082,1/30/2019 17:50,1/30/2019 18:35,34.046951,-118.446785,Los Angeles,CA,62.1,Mostly Cloudy,Day,2019
172853,A-685083,1/30/2019 17:50,1/30/2019 18:35,34.068298,-118.151009,Alhambra,CA,61.0,Clear,Day,2019
172854,A-685084,1/30/2019 17:56,1/30/2019 18:39,33.873997,-117.880302,Fullerton,CA,60.1,Clear,Day,2019
172855,A-685085,1/30/2019 17:57,1/30/2019 18:42,33.872654,-118.341965,Torrance,CA,60.1,Scattered Clouds,Day,2019
172856,A-685086,1/30/2019 18:00,1/30/2019 18:44,32.775562,-117.134842,San Diego,CA,59.0,Clear,Day,2019
172857,A-685087,1/30/2019 18:01,1/30/2019 18:46,34.071594,-118.134666,Alhambra,CA,61.0,Clear,Day,2019
172858,A-685088,1/30/2019 18:02,1/30/2019 18:46,33.876289,-118.125183,Bellflower,CA,60.1,Haze,Day,2019
172859,A-685089,1/30/2019 18:19,1/30/2019 19:04,34.177521,-118.110458,Altadena,CA,NaN,NaN,Day,2019
172860,A-685090,1/30/2019 18:21,1/30/2019 19:06,32.907238,-117.226105,San Diego,CA,57.0,Clear,Day,2019
172861,A-685091,1/30/2019 18:48,1/30/2019 19:33,34.133549,-117.954842,Baldwin Park,CA,60.8,Clear,Night,2019
172862,A-685092,1/30/2019 18:52,1/30/2019 19:37,34.120708,-117.907265,Azusa,CA,60.8,Clear,Night,2019
172863,A-685093,1/30/2019 19:02,1/30/2019 19:46,34.020298,-118.192253,Los Angeles,CA,59.0,Partly Cloudy,Night,2019
172864,A-685094,1/30/2019 20:16,1/30/2019 21:00,34.309063,-117.471786,San Bernardino,CA,57.2,Haze,Night,2019
172865,A-685095,11/30/2018 6:45,11/30/2018 7:14,42.828281,-78.806816,Buffalo,NY,30.9,Overcast,Day,2018
172866,A-685096,11/30/2018 9:08,11/30/2018 9:37,43.083347,-78.823280,North Tonawanda,NY,30.0,Overcast,Day,2018

In [14]:
final_data.to_csv(r'FinalData.csv')